FONT_BITMAP_FILE = "data/fonts/terminal16x16_gs_ro.png"

SCREEN_WIDTH = 70
SCREEN_HEIGHT = 50
HUD_BOARD_HEIGHT = 8

MESSAGE_BOARD_WIDTH = int((SCREEN_WIDTH * 2) / 3)
MESSAGE_BOARD_HEIGHT = HUD_BOARD_HEIGHT

STATUS_BOARD_WIDTH = int(SCREEN_WIDTH / 3)
STATUS_BOARD_HEIGHT = HUD_BOARD_HEIGHT

MAP_WIDTH = SCREEN_WIDTH * 3
MAP_HEIGHT = SCREEN_HEIGHT * 3

BLINK_DELAY = 75 # ms