FONT_BITMAP_FILE = "data/fonts/terminal16x16_gs_ro.png"

SCREEN_WIDTH = 70
SCREEN_HEIGHT = 50

# HOW ARE THESE BOARDS DISPLAYED?
# --------------------
# |      HUD         |
# --------------------
# |                  |
# |   GAME BOARD     |
# |                  |
# --------------------
# |    MSG   | STATS |
# --------------------

MAP_WIDTH = SCREEN_WIDTH * 3
MAP_HEIGHT = SCREEN_HEIGHT * 3

HUD_BOARD_WIDTH = SCREEN_WIDTH
HUD_BOARD_HEIGHT = 8

MESSAGE_BOARD_WIDTH = (SCREEN_WIDTH * 2) // 3
MESSAGE_BOARD_HEIGHT = HUD_BOARD_HEIGHT

STATUS_BOARD_WIDTH = SCREEN_WIDTH // 3
STATUS_BOARD_HEIGHT = HUD_BOARD_HEIGHT

GAME_BOARD_WIDTH = SCREEN_WIDTH
GAME_BOARD_HEIGHT = SCREEN_HEIGHT - (HUD_BOARD_HEIGHT + MESSAGE_BOARD_HEIGHT)

BLINK_DELAY = 75 # ms